import { FastifyInstance } from 'fastify';
import pg from 'pg';
import { createLogger } from '@sven/shared';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';

const logger = createLogger('admin-settings');

type ParsedAdmin47Access = {
  enabled: boolean;
  allowedIps: string[];
  renderedConf: string;
};

type SsoProviderConfig = {
  enabled: boolean;
  issuer_url?: string;
  client_id?: string;
  client_secret?: string;
  authorization_endpoint?: string;
  token_endpoint?: string;
  userinfo_endpoint?: string;
  scopes?: string;
  entrypoint_url?: string;
  entity_id?: string;
  cert_pem?: string;
  callback_url?: string;
};

type SsoConfig = {
  enabled: boolean;
  fallback_local_auth: boolean;
  oidc: SsoProviderConfig;
  saml: SsoProviderConfig;
  jit: { enabled: boolean; default_role: string };
  group_mapping: Array<{ external_group: string; tenant_role: string }>;
};

type FileTarget = {
  dirPath: string;
  fileName: string;
  filePath: string;
};

type ShellCommandResult = {
  ok: boolean;
  code: number | null;
  output: string;
  timedOut: boolean;
};

function parseBool(value: unknown, defaultValue = false): boolean {
  if (typeof value === 'boolean') return value;
  if (typeof value === 'string') {
    const v = value.trim().toLowerCase();
    if (v === 'true' || v === '1' || v === 'yes' || v === 'on') return true;
    if (v === 'false' || v === '0' || v === 'no' || v === 'off') return false;
  }
  if (typeof value === 'number') return value !== 0;
  return defaultValue;
}

function parseOptionalBoolean(raw: unknown): { valid: boolean; value: boolean | undefined } {
  if (raw === undefined) {
    return { valid: true, value: undefined };
  }
  if (typeof raw !== 'boolean') {
    return { valid: false, value: undefined };
  }
  return { valid: true, value: raw };
}

function toStringValue(value: unknown): string {
  if (typeof value === 'string') return value;
  if (Array.isArray(value)) return value.map((v) => String(v)).join(',');
  if (value === null || value === undefined) return '';
  return String(value);
}

function isValidIpOrCidr(candidate: string): boolean {
  // Keep this intentionally strict to avoid config injection.
  if (!/^[0-9A-Fa-f:./]+$/.test(candidate)) return false;
  if (candidate.includes('..') || candidate.includes('//')) return false;
  if (candidate.startsWith('/') || candidate.endsWith('/')) return false;
  return true;
}

function parseAllowedIps(value: unknown): string[] {
  const raw = toStringValue(value);
  if (!raw) return [];
  return raw
    .split(/[\s,]+/)
    .map((s) => s.trim())
    .filter(Boolean)
    .filter(isValidIpOrCidr);
}

function renderAdmin47AccessConf(allowedIps: string[]): string {
  const unique = Array.from(new Set(allowedIps));
  const lines = [
    '# Generated by gateway-api admin settings sync.',
    'allow 127.0.0.1;',
    'allow ::1;',
    ...unique.map((ip) => `allow ${ip};`),
    'deny all;',
    '',
  ];
  return lines.join('\n');
}

function sanitizeSsoConfig(raw: unknown): SsoConfig {
  const input = raw && typeof raw === 'object' ? (raw as Record<string, unknown>) : {};
  const oidcIn = input.oidc && typeof input.oidc === 'object' ? (input.oidc as Record<string, unknown>) : {};
  const samlIn = input.saml && typeof input.saml === 'object' ? (input.saml as Record<string, unknown>) : {};
  const jitIn = input.jit && typeof input.jit === 'object' ? (input.jit as Record<string, unknown>) : {};
  const mapIn = Array.isArray(input.group_mapping) ? input.group_mapping : [];
  const validTenantRoles = new Set(['owner', 'admin', 'operator', 'member', 'viewer']);

  const validateSsoUrl = (value: unknown): string | undefined => {
    const s = toStringValue(value).trim();
    if (!s) return undefined;
    try {
      const u = new URL(s);
      if (u.protocol !== 'https:' && u.protocol !== 'http:') return undefined;
      const h = u.hostname.toLowerCase();
      if (h === 'localhost' || h === '127.0.0.1' || h === '::1' || h === '0.0.0.0' || h === '169.254.169.254' || h === 'metadata.google.internal') return undefined;
      const v4 = h.split('.');
      if (v4.length === 4 && v4.every((p: string) => /^\d+$/.test(p))) {
        const [a, b] = v4.map(Number);
        if (a === 10 || a === 127 || a === 0 || (a === 172 && b >= 16 && b <= 31) || (a === 192 && b === 168) || (a === 169 && b === 254)) return undefined;
      }
      return u.toString();
    } catch { return undefined; }
  };

  const toProvider = (provider: Record<string, unknown>): SsoProviderConfig => ({
    enabled: parseBool(provider.enabled, false),
    issuer_url: validateSsoUrl(provider.issuer_url),
    client_id: toStringValue(provider.client_id) || undefined,
    client_secret: toStringValue(provider.client_secret) || undefined,
    authorization_endpoint: validateSsoUrl(provider.authorization_endpoint),
    token_endpoint: validateSsoUrl(provider.token_endpoint),
    userinfo_endpoint: validateSsoUrl(provider.userinfo_endpoint),
    scopes: toStringValue(provider.scopes) || undefined,
    entrypoint_url: validateSsoUrl(provider.entrypoint_url),
    entity_id: toStringValue(provider.entity_id) || undefined,
    cert_pem: toStringValue(provider.cert_pem) || undefined,
    callback_url: validateSsoUrl(provider.callback_url),
  });

  const group_mapping = mapIn
    .map((row) => (row && typeof row === 'object' ? row as Record<string, unknown> : null))
    .filter(Boolean)
    .map((row) => {
      const external_group = toStringValue((row as Record<string, unknown>).external_group).trim();
      const tenant_role = toStringValue((row as Record<string, unknown>).tenant_role).trim();
      return { external_group, tenant_role };
    })
    .filter((row) => row.external_group && validTenantRoles.has(row.tenant_role));

  const defaultRoleRaw = toStringValue(jitIn.default_role).trim().toLowerCase();
  const default_role = validTenantRoles.has(defaultRoleRaw) ? defaultRoleRaw : 'member';

  return {
    enabled: parseBool(input.enabled, false),
    fallback_local_auth: parseBool(input.fallback_local_auth, true),
    oidc: toProvider(oidcIn),
    saml: toProvider(samlIn),
    jit: {
      enabled: parseBool(jitIn.enabled, true),
      default_role,
    },
    group_mapping,
  };
}

function redactSsoConfig(input: SsoConfig): SsoConfig {
  const clone = JSON.parse(JSON.stringify(input)) as SsoConfig;
  if (clone.oidc.client_secret) clone.oidc.client_secret = '***';
  if (clone.saml.cert_pem) clone.saml.cert_pem = '***';
  return clone;
}

const GENERIC_SETTINGS_SENSITIVE_KEYS = new Set(['auth.sso.config']);
const CONFIG_AUDIT_REDACTED_VALUE = '***';
const CONFIG_AUDIT_SENSITIVE_FIELD_PATTERN = /(secret|token|password|api[_-]?key|cert_pem|private[_-]?key|authorization|cookie)/i;

function sanitizeGenericSettingRow(row: Record<string, unknown>): Record<string, unknown> {
  const key = String(row.key || '');
  if (key === 'auth.sso.config') {
    const parsed = sanitizeSsoConfig(row.value || {});
    return { ...row, value: redactSsoConfig(parsed) };
  }
  return row;
}

function redactConfigAuditValue(value: unknown, keyHint?: string): unknown {
  const key = String(keyHint || '').trim().toLowerCase();
  if (key && CONFIG_AUDIT_SENSITIVE_FIELD_PATTERN.test(key)) {
    return CONFIG_AUDIT_REDACTED_VALUE;
  }
  if (Array.isArray(value)) {
    return value.map((item) => redactConfigAuditValue(item));
  }
  if (value && typeof value === 'object') {
    const output: Record<string, unknown> = {};
    for (const [nestedKey, nestedValue] of Object.entries(value as Record<string, unknown>)) {
      output[nestedKey] = redactConfigAuditValue(nestedValue, nestedKey);
    }
    return output;
  }
  return value;
}

function sanitizeAuditValueForKey(settingKey: string, value: unknown): unknown {
  if (value === undefined) return undefined;
  if (value === null) return null;
  if (settingKey === 'auth.sso.config') {
    return redactConfigAuditValue(value);
  }
  return value;
}

function sanitizeConfigAuditRow(row: Record<string, unknown>): Record<string, unknown> {
  const key = String(row.key || '');
  return {
    ...row,
    old_value: sanitizeAuditValueForKey(key, row.old_value),
    new_value: sanitizeAuditValueForKey(key, row.new_value),
  };
}

function hasOwn(obj: Record<string, unknown> | undefined, key: string): boolean {
  return Boolean(obj && Object.prototype.hasOwnProperty.call(obj, key));
}

function resolveTargetPath(): FileTarget {
  const dirPath = process.env.SVEN_EDGE_ADMIN47_ACCESS_DIR || '/etc/nginx/conf.d/sven-admin47-access';
  const fileName = process.env.SVEN_EDGE_ADMIN47_ACCESS_FILE || 'allowlist.conf';
  if (!path.isAbsolute(dirPath)) {
    throw new Error('SVEN_EDGE_ADMIN47_ACCESS_DIR must be an absolute path');
  }
  if (path.basename(fileName) !== fileName || !/^[A-Za-z0-9._-]+\.conf$/.test(fileName)) {
    throw new Error('SVEN_EDGE_ADMIN47_ACCESS_FILE must be a simple *.conf filename');
  }
  const filePath = path.join(dirPath, fileName);
  const resolvedDir = path.resolve(dirPath);
  const resolvedFile = path.resolve(filePath);
  if (!resolvedFile.startsWith(resolvedDir + path.sep)) {
    throw new Error('Resolved file path escapes target directory');
  }
  return { dirPath, fileName, filePath };
}

async function runShellCommand(command: string): Promise<ShellCommandResult> {
  const timeoutMs = (() => {
    const raw = process.env.SVEN_EDGE_SYNC_SHELL_TIMEOUT_MS;
    const parsed = Number.parseInt(String(raw || '15000'), 10);
    if (!Number.isFinite(parsed) || parsed < 1000) return 15000;
    return Math.min(parsed, 120000);
  })();
  const shell = process.platform === 'win32' ? 'cmd.exe' : '/bin/sh';
  const args = process.platform === 'win32' ? ['/d', '/s', '/c', command] : ['-lc', command];

  const child = spawn(shell, args, { stdio: ['ignore', 'pipe', 'pipe'] });
  let output = '';
  child.stdout.on('data', (chunk) => {
    output += String(chunk);
  });
  child.stderr.on('data', (chunk) => {
    output += String(chunk);
  });

  let timedOut = false;
  const code = await new Promise<number | null>((resolve) => {
    let settled = false;
    const finish = (exitCode: number | null) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeoutHandle);
      resolve(exitCode);
    };

    const timeoutHandle = setTimeout(() => {
      timedOut = true;
      try {
        child.kill('SIGTERM');
      } catch {
        // best-effort termination
      }
      setTimeout(() => {
        try {
          child.kill('SIGKILL');
        } catch {
          // best-effort termination
        }
      }, 500);
      finish(null);
    }, timeoutMs);

    child.on('close', (exitCode) => finish(exitCode));
    child.on('error', () => finish(null));
  });

  return { ok: code === 0 && !timedOut, code, output: output.trim(), timedOut };
}

async function loadAdmin47AccessPolicy(pool: pg.Pool, orgId: string): Promise<ParsedAdmin47Access> {
  const keys = ['edge.admin47.ip_lock_enabled', 'edge.admin47.allowed_ips'];
  const result = await pool.query(
    `SELECT key, value
     FROM organization_settings
     WHERE organization_id = $1 AND key = ANY($2)`,
    [orgId, keys],
  );

  const map = new Map<string, unknown>();
  for (const row of result.rows) map.set(String(row.key), row.value);

  const enabled = parseBool(map.get('edge.admin47.ip_lock_enabled'), false);
  const allowedIps = parseAllowedIps(map.get('edge.admin47.allowed_ips'));
  const renderedConf = renderAdmin47AccessConf(allowedIps);

  return { enabled, allowedIps, renderedConf };
}

export async function registerSettingsRoutes(app: FastifyInstance, pool: pg.Pool) {
  app.addHook('preHandler', async (request: any, reply) => {
    const tenantRole = String(request.tenantRole || '').trim();
    if (tenantRole === 'owner' || tenantRole === 'admin') return;
    return reply.status(403).send({
      success: false,
      error: { code: 'FORBIDDEN', message: 'Insufficient tenant permissions' },
    });
  });

  function currentOrgId(request: any): string | null {
    return request.orgId ? String(request.orgId) : null;
  }

  async function writeConfigAuditEntry(params: {
    organizationId: string;
    key: string;
    oldValue: unknown;
    newValue: unknown;
    changedBy: string;
    changedByUserId: string | null;
    sourceIp: string | null;
    userAgent: string | null;
  }): Promise<void> {
    const oldValueSanitized = sanitizeAuditValueForKey(params.key, params.oldValue);
    const newValueSanitized = sanitizeAuditValueForKey(params.key, params.newValue);
    await pool.query(
      `INSERT INTO config_change_audit
         (organization_id, key, old_value, new_value, changed_at, changed_by, changed_by_user_id, source_ip, user_agent)
       VALUES ($1, $2, $3::jsonb, $4::jsonb, NOW(), $5, $6, $7, $8)`,
      [
        params.organizationId,
        params.key,
        oldValueSanitized === undefined ? null : JSON.stringify(oldValueSanitized),
        newValueSanitized === undefined ? null : JSON.stringify(newValueSanitized),
        params.changedBy,
        params.changedByUserId,
        params.sourceIp,
        params.userAgent,
      ],
    );
  }

  // ─── GET /settings ───
  app.get('/settings', async (request, reply) => {
    const orgId = currentOrgId(request);
    if (!orgId) {
      return reply.status(403).send({ success: false, error: { code: 'ORG_REQUIRED', message: 'Active account required' } });
    }
    const result = await pool.query(
      `SELECT key, value, updated_at, updated_by
       FROM organization_settings
       WHERE organization_id = $1
       ORDER BY key`,
      [orgId],
    );
    reply.send({
      success: true,
      data: result.rows.map((row) => sanitizeGenericSettingRow(row as Record<string, unknown>)),
    });
  });

  // ─── GET /settings/audit ───
  app.get('/settings/audit', async (request, reply) => {
    const orgId = currentOrgId(request);
    if (!orgId) {
      return reply.status(403).send({ success: false, error: { code: 'ORG_REQUIRED', message: 'Active account required' } });
    }

    const query = request.query as { key?: string; limit?: string } | undefined;
    const keyFilter = typeof query?.key === 'string' ? query.key.trim() : '';
    const parsedLimit = Number.parseInt(String(query?.limit || '100'), 10);
    const limit = Number.isFinite(parsedLimit) ? Math.min(Math.max(parsedLimit, 1), 500) : 100;

    const params: unknown[] = [orgId];
    let sql = `
      SELECT id, organization_id, key, old_value, new_value, changed_at, changed_by, changed_by_user_id, source_ip, user_agent
      FROM config_change_audit
      WHERE organization_id = $1`;

    if (keyFilter) {
      params.push(keyFilter);
      sql += ` AND key = $${params.length}`;
    }

    params.push(limit);
    sql += ` ORDER BY changed_at DESC LIMIT $${params.length}`;

    const result = await pool.query(sql, params);
    reply.send({
      success: true,
      data: result.rows.map((row) => sanitizeConfigAuditRow(row as Record<string, unknown>)),
    });
  });

  // ─── GET /settings/:key ───
  app.get('/settings/:key', async (request, reply) => {
    const orgId = currentOrgId(request);
    if (!orgId) {
      return reply.status(403).send({ success: false, error: { code: 'ORG_REQUIRED', message: 'Active account required' } });
    }
    const { key } = request.params as { key: string };
    if (GENERIC_SETTINGS_SENSITIVE_KEYS.has(key)) {
      return reply.status(403).send({
        success: false,
        error: {
          code: 'SENSITIVE_SETTING_RESTRICTED',
          message: 'Use /settings/sso for SSO configuration reads',
        },
      });
    }
    const result = await pool.query(
      `SELECT key, value, updated_at, updated_by
       FROM organization_settings
       WHERE organization_id = $1 AND key = $2`,
      [orgId, key],
    );
    if (result.rows.length === 0) {
      reply.send({
        success: true,
        data: {
          key,
          value: null,
          updated_at: null,
          updated_by: null,
        },
      });
      return;
    }
    reply.send({ success: true, data: sanitizeGenericSettingRow(result.rows[0] as Record<string, unknown>) });
  });

  // ─── PUT /settings/:key ───
  app.put('/settings/:key', async (request, reply) => {
    const orgId = currentOrgId(request);
    if (!orgId) {
      return reply.status(403).send({ success: false, error: { code: 'ORG_REQUIRED', message: 'Active account required' } });
    }
    const { key } = request.params as { key: string };
    const body = request.body as { value?: unknown } | null;

    if (!body || body.value === undefined) {
      reply.status(400).send({ success: false, error: { code: 'VALIDATION', message: 'value is required' } });
      return;
    }

    if (!key || key.length > 255) {
      reply.status(400).send({ success: false, error: { code: 'VALIDATION', message: 'key must be 1-255 characters' } });
      return;
    }

    const previous = await pool.query(
      `SELECT value
       FROM organization_settings
       WHERE organization_id = $1 AND key = $2`,
      [orgId, key],
    );
    const oldValue = previous.rows.length ? previous.rows[0]?.value : null;

    const res = await pool.query(
      `INSERT INTO organization_settings (organization_id, key, value, updated_at, updated_by)
       VALUES ($1, $2, $3, NOW(), $4)
       ON CONFLICT (organization_id, key) DO UPDATE
       SET value = $3, updated_at = NOW(), updated_by = $4
       RETURNING key, value, updated_at`,
      [orgId, key, JSON.stringify(body.value), (request as any).userId],
    );

    const actorUserId = (request as any).userId ? String((request as any).userId) : null;
    const actorName = (request as any).username
      ? String((request as any).username)
      : actorUserId || 'unknown';
    const sourceIp = request.ip ? String(request.ip) : null;
    const userAgentHeader = request.headers['user-agent'];
    const userAgent = typeof userAgentHeader === 'string' ? userAgentHeader : null;

    await writeConfigAuditEntry({
      organizationId: orgId,
      key,
      oldValue,
      newValue: body.value,
      changedBy: actorName,
      changedByUserId: actorUserId,
      sourceIp,
      userAgent,
    });

    logger.info('Setting updated', { key });
    reply.send({ success: true, data: res.rows[0] });
  });

  // ─── GET /settings/edge/admin47/access ───
  app.get('/settings/edge/admin47/access', async (request, reply) => {
    const orgId = currentOrgId(request);
    if (!orgId) {
      return reply.status(403).send({ success: false, error: { code: 'ORG_REQUIRED', message: 'Active account required' } });
    }

    const parsed = await loadAdmin47AccessPolicy(pool, orgId);
    return reply.send({
      success: true,
      data: {
        enabled: parsed.enabled,
        allowed_ips: parsed.allowedIps,
        rendered_conf: parsed.renderedConf,
      },
    });
  });

  // ─── POST /settings/edge/admin47/access/sync ───
  app.post('/settings/edge/admin47/access/sync', async (request, reply) => {
    const orgId = currentOrgId(request);
    if (!orgId) {
      return reply.status(403).send({ success: false, error: { code: 'ORG_REQUIRED', message: 'Active account required' } });
    }
    const isGlobalAdmin = String((request as any).userRole || '').trim() === 'platform_admin';
    if (!isGlobalAdmin) {
      return reply.status(403).send({
        success: false,
        error: { code: 'FORBIDDEN', message: 'Global admin privileges required' },
      });
    }

    const syncEnabled = parseBool(process.env.SVEN_EDGE_ADMIN47_SYNC_ENABLED, false);
    if (!syncEnabled) {
      return reply.status(503).send({
        success: false,
        error: {
          code: 'SYNC_DISABLED',
          message: 'Edge sync is disabled. Set SVEN_EDGE_ADMIN47_SYNC_ENABLED=true to enable server-side nginx sync.',
        },
      });
    }

    const body = (request.body || {}) as { reload?: boolean; reason?: string };
    const reloadParsed = parseOptionalBoolean((body as { reload?: unknown }).reload);
    if (!reloadParsed.valid) {
      return reply.status(400).send({
        success: false,
        error: {
          code: 'VALIDATION',
          message: 'reload must be a boolean when provided',
        },
      });
    }
    const reloadRequested = reloadParsed.value ?? true;
    const reason = String(body.reason || '').trim();
    if (!reason || reason.length < 8 || reason.length > 500) {
      return reply.status(400).send({
        success: false,
        error: {
          code: 'VALIDATION',
          message: 'reason is required (8-500 chars) for privileged edge sync operations',
        },
      });
    }

    const parsed = await loadAdmin47AccessPolicy(pool, orgId);
    const allowEmpty = parseBool(process.env.SVEN_EDGE_ADMIN47_ALLOW_EMPTY, false);
    if (parsed.enabled && parsed.allowedIps.length === 0 && !allowEmpty) {
      return reply.status(400).send({
        success: false,
        error: {
          code: 'EMPTY_ALLOWLIST_BLOCKED',
          message:
            'Lock is enabled but no non-local allowlisted IP/CIDR entries exist. Add at least one entry or set SVEN_EDGE_ADMIN47_ALLOW_EMPTY=true to override.',
        },
      });
    }

    let target: FileTarget;
    try {
      target = resolveTargetPath();
    } catch (error) {
      return reply.status(500).send({
        success: false,
        error: {
          code: 'SYNC_PATH_INVALID',
          message: error instanceof Error ? error.message : 'Invalid sync path configuration',
        },
      });
    }

    if (parsed.enabled) {
      await mkdir(target.dirPath, { recursive: true });
      await writeFile(target.filePath, parsed.renderedConf, 'utf8');
    } else {
      // Disabled means no admin path restriction file from this source.
      await rm(target.filePath, { force: true });
    }

    const testCommand = process.env.SVEN_EDGE_NGINX_TEST_CMD || 'nginx -t';
    const testRes = await runShellCommand(testCommand);
    if (testRes.timedOut) {
      return reply.status(504).send({
        success: false,
        error: {
          code: 'NGINX_TEST_TIMEOUT',
          message: 'nginx config test timed out before completion.',
        },
      });
    }
    if (!testRes.ok) {
      return reply.status(500).send({
        success: false,
        error: {
          code: 'NGINX_TEST_FAILED',
          message: 'nginx -t failed; file was written but reload was not attempted.',
        },
      });
    }

    let reloadRes: ShellCommandResult | null = null;
    if (reloadRequested) {
      const reloadCommand = process.env.SVEN_EDGE_NGINX_RELOAD_CMD || 'systemctl reload nginx';
      reloadRes = await runShellCommand(reloadCommand);
      if (reloadRes.timedOut) {
        return reply.status(504).send({
          success: false,
          error: {
            code: 'NGINX_RELOAD_TIMEOUT',
            message: 'nginx reload timed out before completion.',
          },
        });
      }
      if (!reloadRes.ok) {
        return reply.status(500).send({
          success: false,
          error: {
            code: 'NGINX_RELOAD_FAILED',
            message: 'nginx passed config test but reload failed.',
          },
        });
      }
    }

    const dumpCommand = process.env.SVEN_EDGE_NGINX_DUMP_CMD || 'nginx -T';
    const dumpRes = await runShellCommand(dumpCommand);
    if (dumpRes.timedOut) {
      return reply.status(504).send({
        success: false,
        error: {
          code: 'NGINX_DUMP_TIMEOUT',
          message: 'nginx config dump timed out before completion.',
        },
      });
    }
    const includeHookDetected = dumpRes.ok
      ? dumpRes.output.includes('/etc/nginx/conf.d/sven-admin47-access/*.conf')
      : false;

    logger.info('edge admin47 access sync executed', {
      org_id: orgId,
      actor_user_id: (request as any).userId ? String((request as any).userId) : null,
      actor_role: String((request as any).tenantRole || ''),
      user_role: String((request as any).userRole || ''),
      reload_requested: reloadRequested,
      reason,
    });

    return reply.send({
      success: true,
      data: {
        enabled: parsed.enabled,
        allowed_ips: parsed.allowedIps,
        policy_entries_applied: parsed.allowedIps.length,
        nginx_test_ok: testRes.ok,
        nginx_reloaded: reloadRequested,
        nginx_reload_ok: reloadRequested ? Boolean(reloadRes?.ok) : null,
        include_hook_detected: includeHookDetected,
      },
    });
  });

  // ─── GET /settings/sso ───
  app.get('/settings/sso', async (request, reply) => {
    const orgId = currentOrgId(request);
    if (!orgId) {
      return reply.status(403).send({ success: false, error: { code: 'ORG_REQUIRED', message: 'Active account required' } });
    }
    const current = await pool.query(
      `SELECT value
       FROM organization_settings
       WHERE organization_id = $1 AND key = $2
       LIMIT 1`,
      [orgId, 'auth.sso.config'],
    );
    const parsed = sanitizeSsoConfig(current.rows[0]?.value || {});
    return reply.send({ success: true, data: redactSsoConfig(parsed) });
  });

  // ─── PUT /settings/sso ───
  app.put('/settings/sso', async (request, reply) => {
    const orgId = currentOrgId(request);
    if (!orgId) {
      return reply.status(403).send({ success: false, error: { code: 'ORG_REQUIRED', message: 'Active account required' } });
    }
    const body = request.body as unknown;
    const nextConfig = sanitizeSsoConfig(body || {});

    const previous = await pool.query(
      `SELECT value
       FROM organization_settings
       WHERE organization_id = $1 AND key = $2`,
      [orgId, 'auth.sso.config'],
    );
    const oldValue = previous.rows.length ? previous.rows[0]?.value : null;
    const previousConfig = sanitizeSsoConfig(oldValue || {});
    const rawInput = body && typeof body === 'object' ? (body as Record<string, unknown>) : {};
    const rawOidc = rawInput.oidc && typeof rawInput.oidc === 'object'
      ? (rawInput.oidc as Record<string, unknown>)
      : undefined;
    const rawSaml = rawInput.saml && typeof rawInput.saml === 'object'
      ? (rawInput.saml as Record<string, unknown>)
      : undefined;

    // Preserve existing secrets when omitted or redacted by clients.
    if (!hasOwn(rawOidc, 'client_secret') || nextConfig.oidc.client_secret === '***') {
      nextConfig.oidc.client_secret = previousConfig.oidc.client_secret;
    }
    if (!hasOwn(rawSaml, 'cert_pem') || nextConfig.saml.cert_pem === '***') {
      nextConfig.saml.cert_pem = previousConfig.saml.cert_pem;
    }

    const updated = await pool.query(
      `INSERT INTO organization_settings (organization_id, key, value, updated_at, updated_by)
       VALUES ($1, $2, $3, NOW(), $4)
       ON CONFLICT (organization_id, key) DO UPDATE
       SET value = $3, updated_at = NOW(), updated_by = $4
       RETURNING key, value, updated_at`,
      [orgId, 'auth.sso.config', JSON.stringify(nextConfig), (request as any).userId],
    );

    const actorUserId = (request as any).userId ? String((request as any).userId) : null;
    const actorName = (request as any).username
      ? String((request as any).username)
      : actorUserId || 'unknown';
    const sourceIp = request.ip ? String(request.ip) : null;
    const userAgentHeader = request.headers['user-agent'];
    const userAgent = typeof userAgentHeader === 'string' ? userAgentHeader : null;
    await writeConfigAuditEntry({
      organizationId: orgId,
      key: 'auth.sso.config',
      oldValue,
      newValue: nextConfig,
      changedBy: actorName,
      changedByUserId: actorUserId,
      sourceIp,
      userAgent,
    });

    return reply.send({
      success: true,
      data: {
        ...updated.rows[0],
        value: redactSsoConfig(nextConfig),
      },
    });
  });
}
