apiVersion: v1
kind: ConfigMap
metadata:
  name: sven-app-config
data:
  ENVIRONMENT: "staging"
  SVEN_DEPLOYMENT_MODE: "staging-scale"
  CORS_ORIGIN: "https://staging.sven.systems"
  SVEN_PUBLIC_BASE_URL: "https://staging.sven.systems"
  SVEN_ADMIN_BASE_URL: "https://admin.staging.sven.systems"
