apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sven-staging
resources:
  - ../../base
patches:
  - target:
      version: v1
      kind: Namespace
      name: sven
    patch: |-
      - op: replace
        path: /metadata/name
        value: sven-staging
  - path: app-config.yaml
  - path: ingress.yaml
  - path: gateway-api.yaml
  - path: agent-runtime.yaml
  - path: canvas-ui.yaml
  - path: admin-ui.yaml
  - path: image-pull-secrets.yaml
images:
  - name: ghcr.io/47network/thesven-gateway-api
    newTag: staging
  - name: ghcr.io/47network/thesven-agent-runtime
    newTag: staging
  - name: ghcr.io/47network/thesven-canvas-ui
    newTag: staging
  - name: ghcr.io/47network/thesven-admin-ui
    newTag: staging
