module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'wip',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'gateway',
        'runtime',
        'skills',
        'rag',
        'notify',
        'admin-ui',
        'canvas-ui',
        'shared',
        'infra',
        'db',
        'nats',
        'docker',
        'ci',
        'docs',
      ],
    ],
    'subject-case': [2, 'never', ['upper-case']],
  },
};
