services:
  keycloak-sso:
    image: quay.io/keycloak/keycloak:26.0
    command:
      - start-dev
      - --import-realm
      - --http-port=8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
      - ./services/sso/keycloak/realm-sven-test.json:/opt/keycloak/data/import/realm-sven-test.json:ro
