export const RELEASE_NARRATIVE_LABELS = {
  capabilityProof: 'Capability Proof',
  ecosystemReadiness: 'Ecosystem Readiness',
  docAgentVerificationFeed: 'Doc-Agent Verification Feed',
  waveLanes: 'Wave lanes',
  communityOperations: 'Community Operations',
  verifiedPersonaControls: 'Verified-persona community controls active',
} as const;

export const RELEASE_NARRATIVE_COPY = {
  machineVerifiedCoverage: 'Machine-verified competitive coverage',
  communityOperationsDescription:
    'Capability Proof, Ecosystem Readiness, and Doc-Agent Verification Feed for public community operations',
  docAgentFeedDescription:
    'Automated verification and feature evidence updates generated by community doc agents.',
  capabilityProofDescription:
    'Machine-verified competitive coverage surfaced from live release artifacts, not static claims.',
  runtimeCardDescription:
    'Multi-agent flows, scheduler, and approval-gated tool actions.',
  trustCardDescription:
    'Verified personas, moderation policy, and security baselines.',
  capabilityCardFallback:
    'Machine-verified evidence available in Community Operations.',
} as const;

export function formatStatusLabel(value: string | null | undefined): string {
  const normalized = String(value || 'unknown').trim().toLowerCase();
  if (!normalized) return 'Unknown';
  return normalized.charAt(0).toUpperCase() + normalized.slice(1);
}
