param(
  [Parameter(Mandatory = $true)][double]$CrashFreeSessionsPct,
  [Parameter(Mandatory = $true)][double]$AnrFreeSessionsPct,
  [Parameter(Mandatory = $true)][int]$SampleSizeSessions,
  [Parameter(Mandatory = $true)][string]$Source,
  [double]$TargetCrashFreeSessionsPct = 99.5,
  [double]$TargetAnrFreeSessionsPct = 99.9
)

$ErrorActionPreference = 'Stop'

$__svenTempBootstrap = Join-Path $PSScriptRoot 'lib\\set-project-temp-cache.ps1'
if (-not (Test-Path $__svenTempBootstrap)) { $__svenTempBootstrap = Join-Path $PSScriptRoot '..\\lib\\set-project-temp-cache.ps1' }
if (-not (Test-Path $__svenTempBootstrap)) { $__svenTempBootstrap = Join-Path $PSScriptRoot '..\\..\\lib\\set-project-temp-cache.ps1' }
if (Test-Path $__svenTempBootstrap) {
  . $__svenTempBootstrap
  Set-SvenProjectTempAndCache -StartDir $PSScriptRoot
}

$repoRoot = (git rev-parse --show-toplevel).Trim()
if (-not $repoRoot) { throw 'Could not resolve repo root.' }
Set-Location -LiteralPath $repoRoot

$today = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd')
$datedOutPath = Join-Path $repoRoot ("docs\release\evidence\mobile-crash-anr-$today.md")
$latestOutPath = Join-Path $repoRoot 'docs\release\evidence\mobile-crash-anr-latest.md'
$lines = @(
  '# Mobile Crash/ANR Evidence',
  '',
  "date: $(Get-Date -Format 'yyyy-MM-dd')",
  'release: RC',
  "source: $Source",
  '',
  "crash_free_sessions_pct: $CrashFreeSessionsPct",
  "anr_free_sessions_pct: $AnrFreeSessionsPct",
  "sample_size_sessions: $SampleSizeSessions",
  '',
  "target_crash_free_sessions_pct: $TargetCrashFreeSessionsPct",
  "target_anr_free_sessions_pct: $TargetAnrFreeSessionsPct",
  '',
  'notes:',
  '- Generated by scripts/ops/mobile/set-mobile-crash-anr-evidence.ps1'
)

$content = $lines -join "`n"
$content | Out-File -FilePath $datedOutPath -Encoding utf8
$content | Out-File -FilePath $latestOutPath -Encoding utf8
Write-Output "Wrote: $datedOutPath"
Write-Output "Wrote: $latestOutPath"
