-- ---------------------------------------------------------------------------
-- Batch 30 — ASI-Evolve Self-Improvement Engine
-- ---------------------------------------------------------------------------
-- Extends the base evolution engine (20260415160000) with tables for the
-- Learn → Design → Experiment → Analyze self-improvement loop.
-- Tracks improvement proposals, A/B experiments, and rollback history.
-- ---------------------------------------------------------------------------

-- 30.1 — improvement_proposals: ideas generated by the self-improvement loop
CREATE TABLE IF NOT EXISTS improvement_proposals (
  id              TEXT PRIMARY KEY,
  org_id          TEXT NOT NULL,
  domain          TEXT NOT NULL
                    CHECK (domain IN (
                      'skill', 'prompt', 'workflow', 'routing',
                      'scheduling', 'retrieval', 'custom'
                    )),
  phase           TEXT NOT NULL DEFAULT 'learn'
                    CHECK (phase IN ('learn', 'design', 'experiment', 'analyze', 'applied', 'rejected', 'rolled_back')),
  title           TEXT NOT NULL,
  description     TEXT NOT NULL DEFAULT '',
  current_metric  JSONB NOT NULL DEFAULT '{}',
  proposed_change JSONB NOT NULL DEFAULT '{}',
  expected_impact DOUBLE PRECISION NOT NULL DEFAULT 0,
  actual_impact   DOUBLE PRECISION,
  confidence      DOUBLE PRECISION NOT NULL DEFAULT 0.5
                    CHECK (confidence >= 0 AND confidence <= 1),
  evolution_run_id TEXT REFERENCES evolution_runs(id) ON DELETE SET NULL,
  approved_by     TEXT,
  requires_human_approval BOOLEAN NOT NULL DEFAULT false,
  rollback_plan   JSONB NOT NULL DEFAULT '{}',
  metadata        JSONB NOT NULL DEFAULT '{}',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  applied_at      TIMESTAMPTZ,
  expired_at      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_improvement_proposals_org
  ON improvement_proposals (org_id);
CREATE INDEX IF NOT EXISTS idx_improvement_proposals_phase
  ON improvement_proposals (phase);
CREATE INDEX IF NOT EXISTS idx_improvement_proposals_domain
  ON improvement_proposals (domain);
CREATE INDEX IF NOT EXISTS idx_improvement_proposals_org_phase
  ON improvement_proposals (org_id, phase);
CREATE INDEX IF NOT EXISTS idx_improvement_proposals_created
  ON improvement_proposals (created_at DESC);

-- 30.2 — ab_experiments: A/B test tracking for proposed improvements
CREATE TABLE IF NOT EXISTS ab_experiments (
  id              TEXT PRIMARY KEY,
  proposal_id     TEXT NOT NULL REFERENCES improvement_proposals(id) ON DELETE CASCADE,
  org_id          TEXT NOT NULL,
  variant_a       JSONB NOT NULL DEFAULT '{}',
  variant_b       JSONB NOT NULL DEFAULT '{}',
  status          TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'running', 'completed', 'failed', 'cancelled')),
  sample_size     INTEGER NOT NULL DEFAULT 0,
  target_samples  INTEGER NOT NULL DEFAULT 100,
  variant_a_wins  INTEGER NOT NULL DEFAULT 0,
  variant_b_wins  INTEGER NOT NULL DEFAULT 0,
  variant_a_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  variant_b_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  winner          TEXT CHECK (winner IN ('a', 'b', 'inconclusive')),
  significance    DOUBLE PRECISION,
  started_at      TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ab_experiments_proposal
  ON ab_experiments (proposal_id);
CREATE INDEX IF NOT EXISTS idx_ab_experiments_org
  ON ab_experiments (org_id);
CREATE INDEX IF NOT EXISTS idx_ab_experiments_status
  ON ab_experiments (status);
CREATE INDEX IF NOT EXISTS idx_ab_experiments_org_status
  ON ab_experiments (org_id, status);

-- 30.3 — rollback_history: records of rolled-back improvements
CREATE TABLE IF NOT EXISTS rollback_history (
  id              TEXT PRIMARY KEY,
  proposal_id     TEXT NOT NULL REFERENCES improvement_proposals(id) ON DELETE CASCADE,
  org_id          TEXT NOT NULL,
  reason          TEXT NOT NULL DEFAULT '',
  rollback_data   JSONB NOT NULL DEFAULT '{}',
  previous_state  JSONB NOT NULL DEFAULT '{}',
  restored_state  JSONB NOT NULL DEFAULT '{}',
  triggered_by    TEXT NOT NULL DEFAULT 'system'
                    CHECK (triggered_by IN ('system', 'human', 'safety_guard', 'regression')),
  regression_metric TEXT,
  regression_delta  DOUBLE PRECISION,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rollback_history_proposal
  ON rollback_history (proposal_id);
CREATE INDEX IF NOT EXISTS idx_rollback_history_org
  ON rollback_history (org_id);
CREATE INDEX IF NOT EXISTS idx_rollback_history_trigger
  ON rollback_history (triggered_by);

-- 30.4 — Add ASI-Evolve task types to marketplace_tasks
ALTER TABLE marketplace_tasks
    DROP CONSTRAINT IF EXISTS marketplace_tasks_task_type_check;
ALTER TABLE marketplace_tasks
ADD CONSTRAINT marketplace_tasks_task_type_check CHECK (task_type IN (
    'translate', 'write', 'review', 'proofread', 'format',
    'cover_design', 'genre_research', 'design', 'research', 'support',
    'misiuni_post', 'misiuni_verify', 'legal_research', 'print_broker',
    'trend_research', 'author_persona', 'social_post', 'social_analytics',
    'merch_listing', 'product_design',
    'council_deliberate', 'council_vote',
    'memory_remember', 'memory_recall', 'memory_compress',
    'fleet_deploy', 'fleet_benchmark', 'fleet_evict',
    'evolve_propose', 'evolve_experiment', 'evolve_rollback'
  ));

-- 30.5 — Default ASI-Evolve settings
INSERT INTO settings_global (key, value) VALUES
  ('evolve.auto_propose', 'true'),
  ('evolve.require_human_approval_threshold', '0.7'),
  ('evolve.ab_target_samples', '100'),
  ('evolve.max_concurrent_experiments', '3'),
  ('evolve.rollback_on_regression', 'true'),
  ('evolve.regression_threshold', '-0.05')
ON CONFLICT (key) DO NOTHING;
