// ═══════════════════════════════════════════════════════════════════════════
// CustomShapeSpec — LLM-generated procedural shape specification
// Describes a custom avatar form that Sven can take, generated by the
// local LLM from a user's natural-language description.
// ═══════════════════════════════════════════════════════════════════════════

import 'dart:convert';
import 'package:flutter/painting.dart';

/// Procedural shape definition — every field maps to a drawing parameter.
class CustomShapeSpec {
  static const Set<String> allowedBodyTypes = {
    'sphere',
    'bipedal',
    'quadruped',
    'serpentine',
    'amorphous',
    'crystalline',
    'geometric',
    'avian',
  };

  static const Set<String> allowedEyeShapes = {
    'round',
    'slit',
    'compound',
    'visor',
    'diamond',
  };

  static const Set<String> allowedPatternTypes = {
    'none',
    'stripes',
    'spots',
    'circuits',
    'hexgrid',
    'fractal',
  };

  static const Set<String> allowedAuraStyles = {
    'glow',
    'fire',
    'electric',
    'frost',
    'shadow',
    'holy',
  };

  const CustomShapeSpec({
    required this.name,
    required this.description,
    required this.bodyType,
    required this.bodySegments,
    required this.limbCount,
    required this.hasWings,
    required this.hasTail,
    required this.hasHorns,
    required this.hasAntennae,
    required this.eyeCount,
    required this.eyeShape,
    this.extraFeatures = const [],
    required this.primaryHue,
    required this.secondaryHue,
    required this.glowIntensity,
    required this.symmetry,
    required this.spikiness,
    required this.roundness,
    this.patternType = 'none',
    this.auraStyle = 'glow',
    this.icon = '🔮',
    this.traits = const ['Unique', 'Custom', 'Yours'],
  });

  /// Display name (e.g. "Draco", "Crystal Sentinel")
  final String name;

  /// One-line description
  final String description;

  /// Body shape: 'sphere', 'bipedal', 'quadruped', 'serpentine', 'amorphous',
  /// 'crystalline', 'geometric', 'avian'
  final String bodyType;

  /// Number of body segments (1 = monolithic sphere, 2 = head+torso, 3+ = segmented)
  final int bodySegments;

  /// Number of limbs (0 = orb, 2 = humanoid, 4 = quadruped, 6 = insectoid, 8 = octopod)
  final int limbCount;

  final bool hasWings;
  final bool hasTail;
  final bool hasHorns;
  final bool hasAntennae;

  /// Number of eyes (0–6)
  final int eyeCount;

  /// Eye shape: 'round', 'slit', 'compound', 'visor', 'diamond'
  final String eyeShape;

  /// Extra features like 'scales', 'feathers', 'circuits', 'crystals', 'flames'
  final List<String> extraFeatures;

  /// Primary hue 0–360 (HSL)
  final double primaryHue;

  /// Secondary hue 0–360 (HSL)
  final double secondaryHue;

  /// Glow intensity 0.0–1.0
  final double glowIntensity;

  /// Symmetry axes: 1 = bilateral, 2 = quad, 3+ = radial
  final int symmetry;

  /// Spikiness 0.0–1.0 (0 = smooth, 1 = very spiky)
  final double spikiness;

  /// Roundness 0.0–1.0 (0 = angular, 1 = very round)
  final double roundness;

  /// Pattern: 'none', 'stripes', 'spots', 'circuits', 'hexgrid', 'fractal'
  final String patternType;

  /// Aura style: 'glow', 'fire', 'electric', 'frost', 'shadow', 'holy'
  final String auraStyle;

  /// Emoji icon
  final String icon;

  /// Three trait keywords
  final List<String> traits;

  /// Derived: primary Color (used for painter)
  int get primaryArgb {
    final c = HSLColor.fromAHSL(1.0, primaryHue.clamp(0.0, 360.0), 0.75, 0.55);
    final rgb = c.toColor();
    return rgb.toARGB32();
  }

  /// Derived: secondary Color
  int get secondaryArgb {
    final c =
        HSLColor.fromAHSL(1.0, secondaryHue.clamp(0.0, 360.0), 0.70, 0.60);
    final rgb = c.toColor();
    return rgb.toARGB32();
  }

  /// Derived: background gradient
  List<int> get gradientArgb {
    final bg = HSLColor.fromAHSL(1.0, primaryHue.clamp(0.0, 360.0), 0.30, 0.07);
    return [bg.toColor().toARGB32(), primaryArgb, secondaryArgb];
  }

  /// Serialize to JSON for persistence.
  Map<String, dynamic> toJson() => {
        'name': name,
        'description': description,
        'body_type': bodyType,
        'body_segments': bodySegments,
        'limb_count': limbCount,
        'has_wings': hasWings,
        'has_tail': hasTail,
        'has_horns': hasHorns,
        'has_antennae': hasAntennae,
        'eye_count': eyeCount,
        'eye_shape': eyeShape,
        'extra_features': extraFeatures,
        'primary_hue': primaryHue,
        'secondary_hue': secondaryHue,
        'glow_intensity': glowIntensity,
        'symmetry': symmetry,
        'spikiness': spikiness,
        'roundness': roundness,
        'pattern_type': patternType,
        'aura_style': auraStyle,
        'icon': icon,
        'traits': traits,
      };

  /// Deserialize from JSON.
  factory CustomShapeSpec.fromJson(Map<String, dynamic> j) {
    final rawBodyType = ((j['body_type'] as String?) ?? 'sphere').trim();
    final bodyType =
        allowedBodyTypes.contains(rawBodyType) ? rawBodyType : 'sphere';

    final rawEyeShape = ((j['eye_shape'] as String?) ?? 'round').trim();
    final eyeShape =
        allowedEyeShapes.contains(rawEyeShape) ? rawEyeShape : 'round';

    final rawPatternType = ((j['pattern_type'] as String?) ?? 'none').trim();
    final patternType = allowedPatternTypes.contains(rawPatternType)
        ? rawPatternType
        : 'none';

    final rawAuraStyle = ((j['aura_style'] as String?) ?? 'glow').trim();
    final auraStyle =
        allowedAuraStyles.contains(rawAuraStyle) ? rawAuraStyle : 'glow';

    final features = ((j['extra_features'] as List<dynamic>?) ?? const [])
        .map((e) => e.toString().trim())
        .where((e) => e.isNotEmpty)
        .take(12)
        .toList();
    final traits = ((j['traits'] as List<dynamic>?) ?? const [])
        .map((e) => e.toString().trim())
        .where((e) => e.isNotEmpty)
        .take(3)
        .toList();

    return CustomShapeSpec(
      name: ((j['name'] as String?) ?? 'Entity').trim().isEmpty
          ? 'Entity'
          : ((j['name'] as String?) ?? 'Entity').trim(),
      description: ((j['description'] as String?) ?? 'A custom form')
              .trim()
              .isEmpty
          ? 'A custom form'
          : ((j['description'] as String?) ?? 'A custom form').trim(),
      bodyType: bodyType,
      bodySegments:
          ((j['body_segments'] as num?)?.toInt() ?? 1).clamp(1, 8),
      limbCount:
          ((j['limb_count'] as num?)?.toInt() ?? 0).clamp(0, 8),
      hasWings: (j['has_wings'] as bool?) ?? false,
      hasTail: (j['has_tail'] as bool?) ?? false,
      hasHorns: (j['has_horns'] as bool?) ?? false,
      hasAntennae: (j['has_antennae'] as bool?) ?? false,
      eyeCount:
          ((j['eye_count'] as num?)?.toInt() ?? 2).clamp(0, 6),
      eyeShape: eyeShape,
      extraFeatures: features,
      primaryHue:
          (((j['primary_hue'] as num?)?.toDouble() ?? 200).clamp(0, 360))
              .toDouble(),
      secondaryHue:
          (((j['secondary_hue'] as num?)?.toDouble() ?? 280).clamp(0, 360))
              .toDouble(),
      glowIntensity:
          (((j['glow_intensity'] as num?)?.toDouble() ?? 0.5).clamp(0.0, 1.0))
              .toDouble(),
      symmetry: ((j['symmetry'] as num?)?.toInt() ?? 1).clamp(1, 6),
      spikiness:
          (((j['spikiness'] as num?)?.toDouble() ?? 0.3).clamp(0.0, 1.0))
              .toDouble(),
      roundness:
          (((j['roundness'] as num?)?.toDouble() ?? 0.6).clamp(0.0, 1.0))
              .toDouble(),
      patternType: patternType,
      auraStyle: auraStyle,
      icon: ((j['icon'] as String?) ?? '🔮').trim().isEmpty
          ? '🔮'
          : ((j['icon'] as String?) ?? '🔮').trim(),
      traits: traits.isEmpty ? const ['Unique', 'Custom', 'Yours'] : traits,
    );
  }

  /// Encode to a single string for SharedPreferences storage.
  String encode() => jsonEncode(toJson());

  /// Decode from a stored string.
  static CustomShapeSpec? decode(String? s) {
    if (s == null || s.isEmpty) return null;
    try {
      return CustomShapeSpec.fromJson(jsonDecode(s) as Map<String, dynamic>);
    } catch (_) {
      return null;
    }
  }

  /// Create a copy with optional field replacements
  CustomShapeSpec copyWith({
    String? name,
    String? description,
    String? bodyType,
    int? bodySegments,
    int? limbCount,
    bool? hasWings,
    bool? hasTail,
    bool? hasHorns,
    bool? hasAntennae,
    int? eyeCount,
    String? eyeShape,
    List<String>? extraFeatures,
    double? primaryHue,
    double? secondaryHue,
    double? glowIntensity,
    int? symmetry,
    double? spikiness,
    double? roundness,
    String? patternType,
    String? auraStyle,
    String? icon,
    List<String>? traits,
  }) =>
      CustomShapeSpec(
        name: name ?? this.name,
        description: description ?? this.description,
        bodyType: bodyType ?? this.bodyType,
        bodySegments: bodySegments ?? this.bodySegments,
        limbCount: limbCount ?? this.limbCount,
        hasWings: hasWings ?? this.hasWings,
        hasTail: hasTail ?? this.hasTail,
        hasHorns: hasHorns ?? this.hasHorns,
        hasAntennae: hasAntennae ?? this.hasAntennae,
        eyeCount: eyeCount ?? this.eyeCount,
        eyeShape: eyeShape ?? this.eyeShape,
        extraFeatures: extraFeatures ?? this.extraFeatures,
        primaryHue: primaryHue ?? this.primaryHue,
        secondaryHue: secondaryHue ?? this.secondaryHue,
        glowIntensity: glowIntensity ?? this.glowIntensity,
        symmetry: symmetry ?? this.symmetry,
        spikiness: spikiness ?? this.spikiness,
        roundness: roundness ?? this.roundness,
        patternType: patternType ?? this.patternType,
        auraStyle: auraStyle ?? this.auraStyle,
        icon: icon ?? this.icon,
        traits: traits ?? this.traits,
      );

  /// Default fallback shape.
  static const defaultSpec = CustomShapeSpec(
    name: 'Entity',
    description: 'A shape born from your imagination',
    bodyType: 'sphere',
    bodySegments: 1,
    limbCount: 0,
    hasWings: false,
    hasTail: false,
    hasHorns: false,
    hasAntennae: false,
    eyeCount: 2,
    eyeShape: 'round',
    primaryHue: 200,
    secondaryHue: 280,
    glowIntensity: 0.5,
    symmetry: 1,
    spikiness: 0.3,
    roundness: 0.6,
  );
}
