apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sven
resources:
  - namespace.yaml
  - app-config.yaml
  - gateway-api.yaml
  - agent-runtime.yaml
  - canvas-ui.yaml
  - admin-ui.yaml
  - ingress.yaml
