#!/usr/bin/env sh
set -eu

TARGET_FILE="${1:-/srv/sven/staging/env/.env.staging}"
TOPOLOGY="${STAGING_TOPOLOGY:-proxmox-lan-gpu}"
PUBLIC_URL="${SVEN_PUBLIC_BASE_URL:-https://staging.sven.systems}"
ADMIN_URL="${SVEN_ADMIN_BASE_URL:-https://admin.staging.sven.systems}"
INFERENCE_URL="${OLLAMA_URL:-http://sven-inference-01.lan:11434}"
EMBED_URL="${EMBEDDINGS_URL:-$INFERENCE_URL}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(openssl rand -hex 24)}"
COOKIE_SECRET="${COOKIE_SECRET:-$(openssl rand -hex 32)}"
ADAPTER_TOKEN="${SVEN_ADAPTER_TOKEN:-$(openssl rand -hex 24)}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-$(openssl rand -hex 18)}"
OPENSEARCH_PASSWORD="${OPENSEARCH_PASSWORD:-$(openssl rand -hex 20)}"
SEARXNG_SECRET="${SEARXNG_SECRET:-$(openssl rand -hex 24)}"
LITELLM_MASTER_KEY="${LITELLM_MASTER_KEY:-$(openssl rand -hex 24)}"
GRAFANA_ADMIN_PASSWORD="${GRAFANA_ADMIN_PASSWORD:-$(openssl rand -hex 18)}"

mkdir -p "$(dirname "$TARGET_FILE")"

cat > "$TARGET_FILE" <<EOF
# Sven staging on Linux VM
# Generated by scripts/ops/sh/generate-staging-env.sh
# Topology: ${TOPOLOGY}

ENVIRONMENT=staging
NODE_ENV=production
SVEN_DEPLOYMENT_MODE=staging

# Public URLs
SVEN_PUBLIC_BASE_URL=${PUBLIC_URL}
SVEN_ADMIN_BASE_URL=${ADMIN_URL}
CORS_ORIGIN=${PUBLIC_URL}

# Core ports and credentials
GATEWAY_PORT=3000
POSTGRES_USER=sven
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=sven_staging
DATABASE_URL=postgresql://sven:${POSTGRES_PASSWORD}@postgres:5432/sven_staging
COMMUNITY_DATABASE_URL=postgresql://sven:${POSTGRES_PASSWORD}@postgres:5432/sven_staging
NATS_URL=nats://nats:4222
COOKIE_SECRET=${COOKIE_SECRET}
SVEN_ADAPTER_TOKEN=${ADAPTER_TOKEN}

# Admin bootstrap
ADMIN_USERNAME=47
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# Search / retrieval
OPENSEARCH_URL=http://opensearch:9200
OPENSEARCH_USER=admin
OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
OPENSEARCH_DISABLE_SECURITY=true
SEARXNG_SECRET=${SEARXNG_SECRET}
SEARXNG_URL=http://searxng:8080

# Inference
OLLAMA_URL=${INFERENCE_URL}
EMBEDDINGS_ENABLED=true
EMBEDDINGS_PROVIDER=ollama
EMBEDDINGS_URL=${EMBED_URL}
EMBEDDINGS_MODEL=nomic-embed-text
EMBEDDINGS_DIM=768

# Provider keys
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
GOOGLE_API_KEY=
MISTRAL_API_KEY=
LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}

# Linux container-internal storage paths
SVEN_STORAGE_ROOT=/var/lib/sven/artifacts
ARTIFACT_STORAGE_ROOT=/var/lib/sven/artifacts
SVEN_NAS_ROOT=/var/lib/sven/nas
SVEN_INTEGRATION_STORAGE_ROOT=/var/lib/sven/integrations
VOICE_TTS_STORAGE=/var/lib/sven/tts
WAKE_WORD_STORAGE=/var/lib/sven/wake-word
GIT_INGEST_CLONE_ROOT=/var/lib/sven/git

# Linux host bind roots consumed by docker-compose.staging.linux-vm.yml
SVEN_STAGE_ROOT=/srv/sven/staging
SVEN_STAGE_DATA_ROOT=/srv/sven/staging/data
SVEN_STAGE_POSTGRES_DIR=/srv/sven/staging/data/postgres
SVEN_STAGE_PGWAL_DIR=/srv/sven/staging/data/postgres-wal
SVEN_STAGE_NATS_DIR=/srv/sven/staging/data/nats
SVEN_STAGE_OPENSEARCH_DIR=/srv/sven/staging/data/opensearch
SVEN_STAGE_ARTIFACTS_DIR=/srv/sven/staging/data/artifacts
SVEN_STAGE_NAS_DIR=/srv/sven/staging/data/nas
SVEN_STAGE_INTEGRATIONS_DIR=/srv/sven/staging/data/integrations
SVEN_STAGE_TTS_DIR=/srv/sven/staging/data/tts
SVEN_STAGE_WAKE_WORD_DIR=/srv/sven/staging/data/wake-word
SVEN_STAGE_GIT_DIR=/srv/sven/staging/data/git
SVEN_STAGE_BROWSER_PROFILE_DIR=/srv/sven/staging/data/browser-profile
SVEN_STAGE_OLLAMA_DIR=/srv/sven/staging/data/ollama
SVEN_STAGE_PROMETHEUS_DIR=/srv/sven/staging/data/prometheus
SVEN_STAGE_GRAFANA_DIR=/srv/sven/staging/data/grafana
SVEN_STAGE_LOKI_DIR=/srv/sven/staging/data/loki
SVEN_STAGE_LOKI_ARCHIVE_DIR=/srv/sven/staging/data/loki-archive
SVEN_STAGE_SEARXNG_DIR=/srv/sven/staging/data/searxng
SVEN_STAGE_TUNNEL_DIR=/srv/sven/staging/data/tunnel
SVEN_STAGE_BACKUPS_DIR=/srv/sven/staging/backups

# Optional ingestion roots
NAS_INGEST_ROOT=/var/lib/sven/nas
GIT_INGEST_LOCAL_ROOT=/var/lib/sven/nas/git
NOTES_INGEST_ROOT=/var/lib/sven/nas/notes

# Monitoring
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

# Conservative staging defaults
SVEN_INTEGRATION_RUNTIME_EXEC_ENABLED=false
SVEN_INTEGRATION_RUNTIME_RECONCILE_ENABLED=true
SVEN_INTEGRATION_RUNTIME_RECONCILE_INTERVAL_MS=60000
SVEN_INTEGRATION_RUNTIME_AUTOHEAL=false
EOF

echo "Generated $TARGET_FILE"
echo "Topology: $TOPOLOGY"
echo "Inference URL: $INFERENCE_URL"
