// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';

part 'chat_models.freezed.dart';
part 'chat_models.g.dart';

// Top-level helper referenced by @JsonKey(fromJson: ...) on ChatMessage.timestamp.
// Must be top-level so it can be used as an annotation argument.
DateTime _parseNullableDateTime(dynamic value) {
  if (value == null) return DateTime.now();
  final raw = value.toString().trim();
  if (raw.isEmpty) return DateTime.now();

  final parsed = DateTime.tryParse(raw);
  if (parsed != null) return parsed;

  final normalized = raw.replaceFirst(RegExp(r' \([^)]*\)$'), '');
  final match = RegExp(
    r'^(Mon|Tue|Wed|Thu|Fri|Sat|Sun) '
    r'(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) '
    r'(\d{1,2}) '
    r'(\d{4}) '
    r'(\d{2}):(\d{2}):(\d{2}) '
    r'GMT([+-])(\d{2})(\d{2})$',
  ).firstMatch(normalized);
  if (match == null) return DateTime.now();

  const months = <String, int>{
    'Jan': 1,
    'Feb': 2,
    'Mar': 3,
    'Apr': 4,
    'May': 5,
    'Jun': 6,
    'Jul': 7,
    'Aug': 8,
    'Sep': 9,
    'Oct': 10,
    'Nov': 11,
    'Dec': 12,
  };

  final month = months[match.group(2)];
  if (month == null) return DateTime.now();

  final day = int.parse(match.group(3)!);
  final year = int.parse(match.group(4)!);
  final hour = int.parse(match.group(5)!);
  final minute = int.parse(match.group(6)!);
  final second = int.parse(match.group(7)!);
  final sign = match.group(8) == '-' ? -1 : 1;
  final tzHours = int.parse(match.group(9)!);
  final tzMinutes = int.parse(match.group(10)!);
  final offsetMinutes = sign * ((tzHours * 60) + tzMinutes);

  return DateTime.utc(year, month, day, hour, minute, second)
      .subtract(Duration(minutes: offsetMinutes));
}

// ── ChatThreadSummary ─────────────────────────────────────────────────────────

/// Immutable summary of a chat thread shown in the thread list.
///
/// Equality, [copyWith], and [toString] are generated by freezed.
/// [fromJson] uses a custom factory because the server alternates between
/// `last_message_at` and `updated_at` for the timestamp, and maps `name`→`title`.
@freezed
class ChatThreadSummary with _$ChatThreadSummary {
  const factory ChatThreadSummary({
    required String id,
    required String title,

    /// Always empty string on list fetch; populated on detail fetch.
    required String lastMessage,
    required DateTime updatedAt,
    @Default(0) int unreadCount,
    @Default('dm') String type,
    String? channel,
    @Default(0) int messageCount,
    @Default(false) bool isPinned,

    /// Client-side archive flag (not persisted to server).
    @Default(false) bool isArchived,

    /// Client-side tag (not persisted to server — stored in AppState).
    String? tag,
  }) = _ChatThreadSummary;

  factory ChatThreadSummary.fromJson(Map<String, dynamic> json) {
    final raw = json['last_message_at'] ?? json['updated_at'];
    return ChatThreadSummary(
      id: json['id'] as String,
      title: (json['name'] as String?) ?? 'Chat',
      lastMessage: '',
      updatedAt: raw != null ? DateTime.parse(raw as String) : DateTime.now(),
      type: (json['type'] as String?) ?? 'dm',
      channel: json['channel'] as String?,
      messageCount: (json['message_count'] as int?) ?? 0,
    );
  }
}

// ── ChatMessage ───────────────────────────────────────────────────────────────

/// Immutable chat message.
///
/// [copyWith], [==], [hashCode], and [toString] are generated by freezed.
/// [fromJson] is generated by json_serializable; [toJson] likewise.
@freezed
class ChatMessage with _$ChatMessage {
  const factory ChatMessage({
    required String id,
    required String role,
    required String text,

    /// Mapped from JSON key `created_at`; defaults to [DateTime.now] when absent.
    @JsonKey(name: 'created_at', fromJson: _parseNullableDateTime)
    required DateTime timestamp,
    @Default(ChatMessageStatus.sent) ChatMessageStatus status,
    @JsonKey(name: 'sender_name') String? senderName,
    @JsonKey(name: 'content_type') @Default('text') String contentType,
    @JsonKey(name: 'blocks') List<dynamic>? blocks,
    @JsonKey(name: 'chat_id') String? chatId,
    @JsonKey(name: 'queue_id') String? queueId,
    @JsonKey(name: 'queue_position') int? queuePosition,

    /// Set to true when the user edited and re-sent this message.
    @Default(false) bool isEdited,
  }) = _ChatMessage;

  factory ChatMessage.fromJson(Map<String, dynamic> json) =>
      _$ChatMessageFromJson(json);
}

// ── ChatMessageStatus ─────────────────────────────────────────────────────────

enum ChatMessageStatus { sending, sent, failed, queued, streaming }
